// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZMSA10XDNhsV1Zfkl0wwKaIxCEm33xd0',
    appId: '1:724936377132:web:7464d79c11e683a24d2289',
    messagingSenderId: '724936377132',
    projectId: 'attendence-mangment-system',
    authDomain: 'attendence-mangment-system.firebaseapp.com',
    storageBucket: 'attendence-mangment-system.appspot.com',
    measurementId: 'G-V1N7VF2TVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw-oAWiibNY8jV4esv08Ha7HuJC9tTK2I',
    appId: '1:724936377132:android:ee807ad951f13a714d2289',
    messagingSenderId: '724936377132',
    projectId: 'attendence-mangment-system',
    storageBucket: 'attendence-mangment-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoEsUm5AT3K5cLo8yxnHk9zB_P6R27D4g',
    appId: '1:724936377132:ios:17e97efa6aeb649d4d2289',
    messagingSenderId: '724936377132',
    projectId: 'attendence-mangment-system',
    storageBucket: 'attendence-mangment-system.appspot.com',
    iosBundleId: 'com.example.attendenceManagmentSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoEsUm5AT3K5cLo8yxnHk9zB_P6R27D4g',
    appId: '1:724936377132:ios:17e97efa6aeb649d4d2289',
    messagingSenderId: '724936377132',
    projectId: 'attendence-mangment-system',
    storageBucket: 'attendence-mangment-system.appspot.com',
    iosBundleId: 'com.example.attendenceManagmentSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZMSA10XDNhsV1Zfkl0wwKaIxCEm33xd0',
    appId: '1:724936377132:web:a1bf76a9249ff94d4d2289',
    messagingSenderId: '724936377132',
    projectId: 'attendence-mangment-system',
    authDomain: 'attendence-mangment-system.firebaseapp.com',
    storageBucket: 'attendence-mangment-system.appspot.com',
    measurementId: 'G-G9FYV32CVT',
  );
}
